# 設定
@token = Bearer AAAAAAAAAAAAAAAAAAAAAEEaUgEAAAAAIwZpWKU9WxTYbIk2Mc3qkYLOa2I%3DxjLS0MHGWwBKp7xXZ9gTCRSF9xqEx0MB10kCTCxqTQxyb4otZg
@options = attachments.poll_ids,author_id,attachments.media_keys
###
# 最初のツイートの取得
@id = 20
GET  https://api.twitter.com/2/tweets/{{id}}
Authorization: {{token}}

###
# めっちゃリツイートされたツイートの取得
@id = 440322224407314432
GET  https://api.twitter.com/2/tweets/{{id}}
Authorization: {{token}}

###
# めっちゃリツイートされたツイートの取得 オプション付き
@id = 440322224407314432
GET  https://api.twitter.com/2/tweets/{{id}}
?expansions={{options}}
Authorization: {{token}}

###
# 世論調査ツイートの取得
@id = 1028039268030210048
GET  https://api.twitter.com/2/tweets/{{id}}
Authorization: {{token}}


###
# 世論調査ツイートの取得 オプション付き
@id = 1028039268030210048
@expansions = attachments.poll_ids
#,author_id
GET  https://api.twitter.com/2/tweets/{{id}}
?expansions={{options}}
Authorization: {{token}}